version: '3.8'

services:
  app:
    container_name: app
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    restart: on-failure
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'

  db:
    container_name: db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
    restart: always
    environment:
      - .env
    networks:
      - app_network
    volumes:
      - pg-data:/pg-data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      retries: 5

volumes:
  pg-data:

networks:
  app_network:
    driver: bridge
